name: TelegramChat
main: de.Linus122.TelegramChat.Main
version: ${project.version}
authors: [yukihiratype2]
description: Brings minecraft chat to Telegram!
commands:
   telegram:
      description: Main command
      usage: /<command> [token]
      permission: telegram.settoken
   linktelegram:
      description: Main command
      usage: /<command>
      permission: telegram.linktelegram