messages:
  # telegram messages
  general-message-to-mc: "&c[Telegram]&r %s: %s"
  join-message: "`%s joined the game.`"
  quit-message: "`%s left the game.`"
  death-message: "`%s`"
  need-to-link: "Sorry, please link your account with */linktelegram ingame* to use the chat!"
  can-see-but-not-chat: "You can see the chat but you can't chat at the moment. Type */linktelegram ingame* to chat!"
  success-linked: "Success! Linked %s"
  setup-msg: "Congratulations, your bot is working! Have fun with this Plugin."
  # minecraft message:
  general-message-to-telegram: "%s: %s"
  no-permissions: "&cYou don't have permissions to use this!"
  cant-link-console: "&cSorry, but you can't link the console currently."
  need-to-add-bot-first: "&cPlease add a bot to your server first! /telegram"
  get-token: "&aAdd %s to Telegram and send this message to %s: \n%s"
  get-chat-id: "chat id is %s, save this id to group-id in config.yml"
group-id: -1
enable-joinquitmessages: true
enable-deathmessages: true
enable-chatmessages: true
enable-proxy: true
proxy:
  address: "127.0.0.1"
  port: 8001
